app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app_ajout:
#    path:      /ajout
#    defaults:
#        _controller: AppBundle:Default:ajout
